import React from 'react';
import { motion } from 'motion/react';
import { 
  CheckCircle2, 
  ArrowLeft, 
  Zap, 
  Target, 
  BarChart3, 
  Layout, 
  Calendar, 
  MessageSquare,
  Sparkles,
  Rocket
} from 'lucide-react';

interface ProFeaturesProps {
  onBack: () => void;
  onConfirm: () => void;
}

const ProFeatures: React.FC<ProFeaturesProps> = ({ onBack, onConfirm }) => {
  const features = [
    {
      title: "Unlimited Roadmaps",
      desc: "Generate as many career paths as you need. Pivot, explore, and experiment without limits.",
      icon: <Layout className="text-indigo-400" />
    },
    {
      title: "AI Skill Gap Analysis",
      desc: "Deep analysis of your current skills vs. market demands. Know exactly what to learn next.",
      icon: <Target className="text-indigo-400" />
    },
    {
      title: "Project Lab Access",
      desc: "Get curated project ideas tailored to your roadmap to build a world-class portfolio.",
      icon: <Rocket className="text-indigo-400" />
    },
    {
      title: "Weekly Accountability",
      desc: "Stay on track with weekly check-ins and progress reports generated by our AI engine.",
      icon: <Calendar className="text-indigo-400" />
    },
    {
      title: "Priority AI Support",
      desc: "Faster response times and more detailed strategic advice from your AI Career Coach.",
      icon: <MessageSquare className="text-indigo-400" />
    },
    {
      title: "Market Insights",
      desc: "Real-time data on salary trends, hiring demand, and emerging technologies in your field.",
      icon: <BarChart3 className="text-indigo-400" />
    }
  ];

  return (
    <div className="min-h-screen bg-[#020617] text-white py-20 px-6 relative overflow-hidden">
      {/* Background Glows */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-indigo-500/10 blur-[120px] rounded-full" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-purple-500/10 blur-[120px] rounded-full" />

      <div className="max-w-4xl mx-auto relative z-10">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors mb-12 group"
        >
          <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
          Back to Pricing
        </button>

        <div className="text-center mb-20">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-black uppercase tracking-widest mb-6">
            <Zap size={14} />
            Pro Plan
          </div>
          <h1 className="text-5xl md:text-7xl font-black mb-6 tracking-tight">
            Unlock Your <span className="text-indigo-500">Full Potential.</span>
          </h1>
          <p className="text-slate-400 text-xl max-w-2xl mx-auto leading-relaxed">
            The Pro plan is designed for serious professionals who want to accelerate their growth with data-driven strategies and AI-powered accountability.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-20">
          {features.map((feature, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
              className="p-8 rounded-[2.5rem] glass-card border-white/5 hover:border-indigo-500/20 transition-all group"
            >
              <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                {feature.icon}
              </div>
              <h3 className="text-xl font-black mb-3">{feature.title}</h3>
              <p className="text-slate-400 leading-relaxed">{feature.desc}</p>
            </motion.div>
          ))}
        </div>

        <div className="p-12 rounded-[3rem] premium-border glass-dark text-center relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-full bg-indigo-500/5 pointer-events-none" />
          <h2 className="text-3xl font-black mb-4 relative z-10">Ready to level up?</h2>
          <p className="text-slate-400 mb-10 max-w-md mx-auto relative z-10">
            Join thousands of professionals who are already using the Pro plan to reach their career goals faster.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-6 relative z-10">
            <button 
              onClick={onConfirm}
              className="px-12 py-6 bg-indigo-500 text-white font-black rounded-2xl text-xl hover:scale-105 active:scale-95 transition-all shadow-2xl shadow-indigo-500/20"
            >
              Get Pro Access Now
            </button>
            <div className="text-2xl font-black">
              ₹999<span className="text-sm text-slate-500">/mo</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProFeatures;
